Added some error handling to note function

diff --git a/subbash/function b/subbash/function
--- a/subbash/function
+++ b/subbash/function
@@ -103,13 +103,25 @@ function exifclean() {
 ## An aproximation of Notational Velocity and Terminal Velocity
 ## gensub currently replacing
 function note() {
+    ## Original Oneliner
+    #pushd ~/Notes 1>/dev/null && vim $(fzf -i --cycle --reverse --preview-window=down --preview='cat {}' --print-query | gawk 'END{if($0 !~ /.txt$/){$0=gensub(" ","_","g",$0) ".txt"}; print $0}'); popd 1>/dev/null
+
     if [[ $@ != "" ]]; then
         echo "No augments accepted in this function!"
         return 2
     fi
 
-    pushd ~/Notes 1>/dev/null && \
-    vim $(fzf -i --cycle --reverse --preview-window=down --preview='cat {}' --print-query | gawk 'END{if($0 !~ /.txt$/){$0=gensub(" ","_","g",$0) ".txt"}; print $0}')
+    pushd ~/Notes 1>/dev/null
+    if [ $? -ne 0 ]; then
+        echo "Notes dir not found!"
+        return 2
+    fi
+
+    local EDIT_NOTE=$(fzf -i --cycle --reverse --preview-window=down --preview='cat {}' --print-query | gawk 'END{if($0 !~ /.txt$/){$0=gensub(" ","_","g",$0) ".txt"}; print $0}')
+    if [[ ${EDIT_NOTE} != ".txt" ]]; then
+        vim ${EDIT_NOTE}
+    fi
+
     popd 1>/dev/null
 }
 ### End Note ### }}}
